[build]
# This command installs the function's dependencies.
command = "npm install"

# The directory where your website files are.
publish = "."

# The directory where your serverless functions are.
functions = "api"

[functions]
# Increase the timeout for potentially long PDF generation.
# The maximum for the free tier is 26 seconds.
timeout = 25
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200