[build]
command = "npm install"
publish = "."
functions = "api"

[functions]
  node_bundler = "esbuild"
  
  [functions.timeout]
    timeout = 25

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200